package grgr.adventofcode2020;

import java.io.BufferedReader;
import java.io.StringReader;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.junit.jupiter.api.Test;

public class Day05Test {

    String input1 = "abc\n" +
            "\n" +
            "a\n" +
            "b\n" +
            "c\n" +
            "\n" +
            "ab\n" +
            "ac\n" +
            "\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "\n" +
            "b";
    String input2 = "zvxc\n" +
            "dv\n" +
            "vh\n" +
            "xv\n" +
            "jvem\n" +
            "\n" +
            "mxfhdeyikljnz\n" +
            "vwzbjmsrgq\n" +
            "\n" +
            "vbtjnh\n" +
            "vhejnbti\n" +
            "vthnjb\n" +
            "tsbhjnv\n" +
            "\n" +
            "cbjemdvp\n" +
            "jdvuylp\n" +
            "ofpjaqgsrxvdn\n" +
            "dzvpbj\n" +
            "vbktpdj\n" +
            "\n" +
            "knyvdhsemu\n" +
            "sdyumkgvh\n" +
            "muyvdskh\n" +
            "syhkuvmd\n" +
            "dvmykshu\n" +
            "\n" +
            "rmantzovbsuxiljkchfgdqew\n" +
            "vficzosgwlmrdtqkueajbnxh\n" +
            "davqlntibxhojesrkugpzmwfc\n" +
            "\n" +
            "ifdmgrcve\n" +
            "bkqal\n" +
            "gxcwvt\n" +
            "\n" +
            "xeiokblasch\n" +
            "toxjlsbnciha\n" +
            "sovycihlabx\n" +
            "ximhylocabs\n" +
            "hixsolabc\n" +
            "\n" +
            "iyfkvmpolta\n" +
            "thpqodzifxc\n" +
            "\n" +
            "iexunoyhwv\n" +
            "ovweiyuhxn\n" +
            "uhojnvyxeiw\n" +
            "\n" +
            "vbncamhzojtqrlpse\n" +
            "wujapcidzx\n" +
            "zxjiuacwkgfdp\n" +
            "\n" +
            "bygewhzsnqvxaoc\n" +
            "sngqvepohyzdwxcab\n" +
            "yoxwzmgvesbqhcua\n" +
            "cqtbwehiavofzsgylx\n" +
            "\n" +
            "rxanvifdup\n" +
            "xuvpnfria\n" +
            "rfnpvixua\n" +
            "npiuxfarv\n" +
            "vnifuxpra\n" +
            "\n" +
            "ysrktfhc\n" +
            "trfkcysh\n" +
            "ktfycrsh\n" +
            "rhckstyf\n" +
            "\n" +
            "nq\n" +
            "kqin\n" +
            "nq\n" +
            "qn\n" +
            "nq\n" +
            "\n" +
            "yorbujt\n" +
            "evqkmscp\n" +
            "\n" +
            "fitkprweso\n" +
            "fszkmoretwpi\n" +
            "ptyoswrekim\n" +
            "iuwbrsgeockpajt\n" +
            "yewksitpro\n" +
            "\n" +
            "gtyaemflvc\n" +
            "fyvlecgmati\n" +
            "vgfyclemta\n" +
            "\n" +
            "k\n" +
            "tj\n" +
            "uebpy\n" +
            "vyma\n" +
            "ibdy\n" +
            "\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "\n" +
            "r\n" +
            "r\n" +
            "lya\n" +
            "b\n" +
            "r\n" +
            "\n" +
            "cht\n" +
            "hct\n" +
            "cth\n" +
            "tch\n" +
            "hct\n" +
            "\n" +
            "qdxpas\n" +
            "dpxsha\n" +
            "parlyekqsx\n" +
            "sxuotvpwaz\n" +
            "jqxspymae\n" +
            "\n" +
            "ngycrw\n" +
            "wgnv\n" +
            "sngw\n" +
            "\n" +
            "psb\n" +
            "us\n" +
            "s\n" +
            "s\n" +
            "s\n" +
            "\n" +
            "xnodk\n" +
            "dxok\n" +
            "tkxdo\n" +
            "\n" +
            "n\n" +
            "n\n" +
            "n\n" +
            "\n" +
            "tysg\n" +
            "gtys\n" +
            "syg\n" +
            "eghslqry\n" +
            "gyts\n" +
            "\n" +
            "qliwfgatpbdcy\n" +
            "aqwflpdygtcb\n" +
            "ypdcglqtwabf\n" +
            "dwgcytlbapqf\n" +
            "\n" +
            "nwvlqbusparkf\n" +
            "jhfbvnsqpr\n" +
            "nprqbzfevs\n" +
            "nvrqhboexmspfy\n" +
            "\n" +
            "tgr\n" +
            "rgt\n" +
            "gtr\n" +
            "\n" +
            "jokfqv\n" +
            "jqk\n" +
            "qjk\n" +
            "\n" +
            "fuv\n" +
            "mvuf\n" +
            "vfu\n" +
            "\n" +
            "mfw\n" +
            "mwf\n" +
            "fmw\n" +
            "fmw\n" +
            "\n" +
            "kt\n" +
            "jp\n" +
            "\n" +
            "fklnagsztb\n" +
            "znmtsfalpj\n" +
            "\n" +
            "o\n" +
            "qb\n" +
            "\n" +
            "h\n" +
            "peqyon\n" +
            "az\n" +
            "\n" +
            "n\n" +
            "n\n" +
            "\n" +
            "eagyvpmjqxs\n" +
            "qghjsapny\n" +
            "jayrqsgp\n" +
            "qasygjp\n" +
            "\n" +
            "yctzugn\n" +
            "ytzcgu\n" +
            "cuytgz\n" +
            "\n" +
            "bsfxcygptnlk\n" +
            "xrgocylkifuen\n" +
            "\n" +
            "os\n" +
            "wakdftzgh\n" +
            "losn\n" +
            "pn\n" +
            "yp\n" +
            "\n" +
            "pie\n" +
            "ei\n" +
            "\n" +
            "zpsxeb\n" +
            "tgynfiw\n" +
            "zomvqu\n" +
            "ludk\n" +
            "\n" +
            "s\n" +
            "s\n" +
            "\n" +
            "wuon\n" +
            "ngw\n" +
            "wn\n" +
            "nw\n" +
            "wn\n" +
            "\n" +
            "omrdjkzeb\n" +
            "ncdjuzborkm\n" +
            "zkebrdajmo\n" +
            "\n" +
            "tjwaxm\n" +
            "iztwvod\n" +
            "wqt\n" +
            "txwr\n" +
            "wt\n" +
            "\n" +
            "lpcbfwiksnvdhrqjut\n" +
            "punidbscqtrwjvkfhl\n" +
            "vrcqukphwjsdbtflin\n" +
            "dvkwlgnhutsrcjbqipf\n" +
            "\n" +
            "spzlowvtxdkjinfc\n" +
            "indjlksczxfptvo\n" +
            "czmaxkqnfpbvyshjdliot\n" +
            "\n" +
            "aqspmnkxie\n" +
            "trjhfclyogd\n" +
            "zwavixpbeu\n" +
            "\n" +
            "mozewqhxkduajgy\n" +
            "mogjekqnfuywzhxda\n" +
            "ozhkaxegyumwqdj\n" +
            "ajdzogmehwqrkyux\n" +
            "\n" +
            "qemykxdwipjfa\n" +
            "wdxaplmeyfkiqj\n" +
            "xmqplaekifdwzj\n" +
            "mjixwqzaedkfp\n" +
            "ofpmwxkqjeadi\n" +
            "\n" +
            "gpjydb\n" +
            "jpystgkd\n" +
            "gzjdpy\n" +
            "jpgyd\n" +
            "pgjydxh\n" +
            "\n" +
            "drockgqe\n" +
            "evanghozbi\n" +
            "\n" +
            "kfg\n" +
            "lmfwig\n" +
            "gf\n" +
            "fgsj\n" +
            "\n" +
            "zjfnabowyrtmxcgl\n" +
            "ycrjxazgfowbitlnm\n" +
            "hrlwegxokbqzatcnjfmy\n" +
            "jcobagxflzntymwr\n" +
            "grzotfxcymlwavbunj\n" +
            "\n" +
            "iamdhcgfynqzos\n" +
            "gyszifcnavdolhqm\n" +
            "qmnwziuropsacdgyh\n" +
            "\n" +
            "mwlgcedjtknxsuy\n" +
            "estmwlxuydjkci\n" +
            "hctlyawmxkjseud\n" +
            "jutsxdycwlkmie\n" +
            "mtwqyskbflxjzvcdeuo\n" +
            "\n" +
            "sdfwjm\n" +
            "wdsm\n" +
            "ygmqsxdei\n" +
            "\n" +
            "u\n" +
            "u\n" +
            "u\n" +
            "\n" +
            "dutb\n" +
            "dubt\n" +
            "dutb\n" +
            "tdu\n" +
            "idtu\n" +
            "\n" +
            "sqpfzwlvcjtx\n" +
            "haiv\n" +
            "dveyohgb\n" +
            "kuvhm\n" +
            "vik\n" +
            "\n" +
            "myzxofuacqsgi\n" +
            "kcamifojuybgqs\n" +
            "\n" +
            "mthngfuvykwci\n" +
            "numzktjydcxwio\n" +
            "\n" +
            "aspdgtikq\n" +
            "qpkgdtisa\n" +
            "qsgkdptia\n" +
            "pqtuakzdigxs\n" +
            "pdkqtiasg\n" +
            "\n" +
            "fityomxdwlscjazhkqp\n" +
            "pmzrcjhvntsobfq\n" +
            "shztqgmrjofcp\n" +
            "jmcngqhoputzefs\n" +
            "\n" +
            "whjgxi\n" +
            "wxjoihg\n" +
            "gxjwih\n" +
            "\n" +
            "hirpefgxsa\n" +
            "gahfytkz\n" +
            "qdjlzvwfahg\n" +
            "hbaofwgvc\n" +
            "\n" +
            "dhcnfgy\n" +
            "fyhdgc\n" +
            "gyctdhf\n" +
            "\n" +
            "hbmconewlqgsdzk\n" +
            "jqflbowkdsgc\n" +
            "hwkobvdcsqeilgn\n" +
            "lkcogsaypdwxbq\n" +
            "\n" +
            "enzrdgqyu\n" +
            "gvqrtoihlaj\n" +
            "qrgs\n" +
            "qpeurgzkxn\n" +
            "\n" +
            "grjdenycstpfbihqo\n" +
            "bfkhlgjrpeysomtvidqc\n" +
            "\n" +
            "fxmqujr\n" +
            "wmvghur\n" +
            "dpaeyko\n" +
            "\n" +
            "untpyr\n" +
            "urtpyn\n" +
            "apnutry\n" +
            "uptyrn\n" +
            "nustyrepg\n" +
            "\n" +
            "ofualjwvq\n" +
            "jeyoqru\n" +
            "yuxqioj\n" +
            "ushtogmdpqjcknb\n" +
            "\n" +
            "txeyfwrhl\n" +
            "xrhfytelw\n" +
            "\n" +
            "nu\n" +
            "niu\n" +
            "\n" +
            "rbmuneiz\n" +
            "neibzurm\n" +
            "mnerbizu\n" +
            "\n" +
            "mvtkp\n" +
            "vmpkzt\n" +
            "mpvkt\n" +
            "\n" +
            "vakc\n" +
            "erq\n" +
            "b\n" +
            "ijftomxy\n" +
            "zsg\n" +
            "\n" +
            "yptu\n" +
            "tpayoub\n" +
            "\n" +
            "zsqvdfw\n" +
            "zdswvfq\n" +
            "qzwsfdv\n" +
            "qwzdfsv\n" +
            "\n" +
            "pbwvzadgyturskqoefncxhmjl\n" +
            "thazxruyscfqndvpjklbgomwe\n" +
            "\n" +
            "xnomrqyzpe\n" +
            "ieudmxroqvbnz\n" +
            "\n" +
            "cldqr\n" +
            "ecdqr\n" +
            "ercqd\n" +
            "cdwrq\n" +
            "\n" +
            "kwzqcagfxvhjromti\n" +
            "hfsjcqxibokgravztmw\n" +
            "atkrogwjcxvfmzhiq\n" +
            "gwhztkxacfvrimqoj\n" +
            "\n" +
            "ztbqli\n" +
            "lobdrhgt\n" +
            "rbltoyh\n" +
            "\n" +
            "wfh\n" +
            "fh\n" +
            "hf\n" +
            "fh\n" +
            "\n" +
            "rnxkztpmi\n" +
            "umzigxnh\n" +
            "zyxilqnsm\n" +
            "\n" +
            "iox\n" +
            "oi\n" +
            "\n" +
            "ovugqjpxkshczewmr\n" +
            "smpgxuqzlehkwrvaocj\n" +
            "civspxkmhjwuzegoqr\n" +
            "jergszqvhkxucpomw\n" +
            "\n" +
            "mzsrlcfqpuaex\n" +
            "rtxaqnsjczvf\n" +
            "rxsuiazqcdf\n" +
            "\n" +
            "zvmltjegwxyfihnsaouq\n" +
            "tmwlgxyhoendfiaq\n" +
            "nrgptwaxleoqfihmyk\n" +
            "tlqhiawmnoyfegx\n" +
            "nhlwfcagqyotxmei\n" +
            "\n" +
            "dfoyublxhzajwktrv\n" +
            "olrfzuyphd\n" +
            "fynohuiqemlszr\n" +
            "\n" +
            "nmwedzq\n" +
            "qewzdn\n" +
            "zqnedw\n" +
            "qnzwedp\n" +
            "dqezwn\n" +
            "\n" +
            "lvugjzmsec\n" +
            "mgnlqsjzudvw\n" +
            "\n" +
            "yasmrkxvnpch\n" +
            "yxabnvhpskrdmcl\n" +
            "hvnkarsyxpmc\n" +
            "myhvconkpaxrs\n" +
            "\n" +
            "pfelbgs\n" +
            "a\n" +
            "vriu\n" +
            "\n" +
            "vfy\n" +
            "oj\n" +
            "izagebph\n" +
            "ck\n" +
            "mv\n" +
            "\n" +
            "hn\n" +
            "h\n" +
            "bjhtr\n" +
            "h\n" +
            "h\n" +
            "\n" +
            "saixpwbhqdverzcyfnktluo\n" +
            "kuqtfhewypnrbgvcdliozxs\n" +
            "deiyptgkwrzqlohbvxfucsn\n" +
            "bynqihpjwecotlfvzusdrkx\n" +
            "\n" +
            "yxvfnlwz\n" +
            "ecvwlfbgnz\n" +
            "rfphonqviwlz\n" +
            "nezbwvufl\n" +
            "\n" +
            "i\n" +
            "i\n" +
            "i\n" +
            "i\n" +
            "i\n" +
            "\n" +
            "hvbatqdzu\n" +
            "zvaqtumldb\n" +
            "\n" +
            "hqxbn\n" +
            "hqbn\n" +
            "hqbn\n" +
            "\n" +
            "ymikcgxdph\n" +
            "kmduhyxqenpil\n" +
            "kphygxmid\n" +
            "hidfkzxypm\n" +
            "\n" +
            "gve\n" +
            "eygv\n" +
            "\n" +
            "chds\n" +
            "hsdc\n" +
            "dcsh\n" +
            "hcsd\n" +
            "\n" +
            "pgakuncrze\n" +
            "rpackxegnz\n" +
            "\n" +
            "nhypde\n" +
            "ncepyd\n" +
            "ndpey\n" +
            "ydenp\n" +
            "yecndp\n" +
            "\n" +
            "qgjpeu\n" +
            "dfma\n" +
            "uwnfvsja\n" +
            "ohxcltz\n" +
            "\n" +
            "emgqlacpfvjhux\n" +
            "iudjrhwvfsxplmge\n" +
            "\n" +
            "fmwbpeyxna\n" +
            "wxdnafyeuibkj\n" +
            "\n" +
            "rqhzeaojuigyvp\n" +
            "ovtixs\n" +
            "ixov\n" +
            "\n" +
            "ms\n" +
            "m\n" +
            "\n" +
            "u\n" +
            "v\n" +
            "u\n" +
            "u\n" +
            "\n" +
            "yo\n" +
            "yo\n" +
            "yo\n" +
            "\n" +
            "rhnmlxbvdteckzpsjaw\n" +
            "cwzdraljthpnkxmeibvs\n" +
            "wavdlhjezskmbrnpcxt\n" +
            "pqadwkrmjbecxlnsthzv\n" +
            "zkpbawrdhnclsmtexvj\n" +
            "\n" +
            "djecv\n" +
            "jewcd\n" +
            "dejcb\n" +
            "dvjce\n" +
            "ecdj\n" +
            "\n" +
            "adiotklhj\n" +
            "oakyljdthi\n" +
            "laticokjdh\n" +
            "cialdtykjhfo\n" +
            "kadoequjtlih\n" +
            "\n" +
            "xcrfloupby\n" +
            "lufciypr\n" +
            "hrpcuyxfl\n" +
            "\n" +
            "fwngabh\n" +
            "njfgbwha\n" +
            "hgafbwn\n" +
            "bnhgawf\n" +
            "fbamhngw\n" +
            "\n" +
            "fwqe\n" +
            "qfmvup\n" +
            "fqa\n" +
            "fqe\n" +
            "\n" +
            "us\n" +
            "us\n" +
            "su\n" +
            "su\n" +
            "\n" +
            "lobh\n" +
            "b\n" +
            "bezjmi\n" +
            "iblz\n" +
            "sxbtav\n" +
            "\n" +
            "tjkdlfwm\n" +
            "klwmjfdt\n" +
            "lcwfvjmdktq\n" +
            "wlkfdtjm\n" +
            "kmdwltfj\n" +
            "\n" +
            "ngrzftbhoevylpiscd\n" +
            "rhvsfbliwkndcaxzoejyp\n" +
            "pfizbnldechsryov\n" +
            "csnrdfibyvpolzeh\n" +
            "\n" +
            "bhszfutjkrdxyeic\n" +
            "iscrkhbjwdlyxzefp\n" +
            "\n" +
            "rncodaythzpgelbu\n" +
            "udcnathrbsogelzy\n" +
            "yuhwglzreancitojbd\n" +
            "yhelzuodacnrbtg\n" +
            "\n" +
            "rv\n" +
            "fwla\n" +
            "\n" +
            "cuqsfzalw\n" +
            "caqzwlfus\n" +
            "wvcuflszaq\n" +
            "saqlcuzfw\n" +
            "uwscqaflz\n" +
            "\n" +
            "hnp\n" +
            "pnh\n" +
            "\n" +
            "y\n" +
            "y\n" +
            "ergy\n" +
            "y\n" +
            "y\n" +
            "\n" +
            "bmexpongud\n" +
            "pgktrwhbneqaxov\n" +
            "uiocxdgnebps\n" +
            "\n" +
            "vxtckwno\n" +
            "uenb\n" +
            "\n" +
            "xgomqzsuivnab\n" +
            "xusnvoqimgbza\n" +
            "vqizsuxbnamgo\n" +
            "zumvgxansqboi\n" +
            "\n" +
            "s\n" +
            "tsy\n" +
            "lf\n" +
            "rczxhvaopjew\n" +
            "ltm\n" +
            "\n" +
            "ipvefjzuhs\n" +
            "hiecsvzu\n" +
            "egykiushqbzdmovx\n" +
            "izhvesau\n" +
            "virsuhez\n" +
            "\n" +
            "ld\n" +
            "lg\n" +
            "\n" +
            "xnvszluechwptgm\n" +
            "uczsgowtpvlnmx\n" +
            "zmwglrpscuvtxyn\n" +
            "xmcstnvldzpguaw\n" +
            "miwblxuzgcptjvksnq\n" +
            "\n" +
            "ftwx\n" +
            "zcritxpbo\n" +
            "txsf\n" +
            "\n" +
            "buzcyxlmoknsvqrdpwta\n" +
            "iseplfgmrnjbwyvhtxk\n" +
            "\n" +
            "cmjpkingdflra\n" +
            "pcinrfladmkug\n" +
            "icrmngljadkpf\n" +
            "\n" +
            "saehfjb\n" +
            "dtuheqwbgxyonksjlc\n" +
            "ehvmjsb\n" +
            "\n" +
            "fcty\n" +
            "qopy\n" +
            "hyfv\n" +
            "\n" +
            "djkcm\n" +
            "jklmbd\n" +
            "mhrdkji\n" +
            "\n" +
            "xaropbcylemuh\n" +
            "benjalhducrpy\n" +
            "ecypvsklubhtirwfa\n" +
            "azrynhepulcb\n" +
            "\n" +
            "xe\n" +
            "xe\n" +
            "xe\n" +
            "ex\n" +
            "\n" +
            "os\n" +
            "os\n" +
            "asob\n" +
            "so\n" +
            "\n" +
            "omtnjhdvcw\n" +
            "ujotewxndvkfb\n" +
            "\n" +
            "svqlbwrctd\n" +
            "qfcbltsh\n" +
            "\n" +
            "eof\n" +
            "ebosn\n" +
            "owfe\n" +
            "xmyoe\n" +
            "rvmoew\n" +
            "\n" +
            "lmaus\n" +
            "ulam\n" +
            "auml\n" +
            "\n" +
            "ky\n" +
            "e\n" +
            "f\n" +
            "o\n" +
            "e\n" +
            "\n" +
            "figyhsul\n" +
            "fguyhlsi\n" +
            "lyhfigsu\n" +
            "yuglfshi\n" +
            "\n" +
            "myc\n" +
            "cmyd\n" +
            "myc\n" +
            "mcy\n" +
            "\n" +
            "dpnbhltm\n" +
            "mp\n" +
            "pmua\n" +
            "opxm\n" +
            "kvpgmuf\n" +
            "\n" +
            "hk\n" +
            "prv\n" +
            "rh\n" +
            "ixm\n" +
            "\n" +
            "umlcksxonaqft\n" +
            "bednjkpgirm\n" +
            "\n" +
            "tj\n" +
            "fxjtl\n" +
            "tcmj\n" +
            "tgzbvoprkqwu\n" +
            "ist\n" +
            "\n" +
            "bzats\n" +
            "haosb\n" +
            "abqsk\n" +
            "abgs\n" +
            "wvbfeuxasn\n" +
            "\n" +
            "knwbzryjvde\n" +
            "jdebkvryzcn\n" +
            "djbzykenv\n" +
            "euyfnkavdzbxmj\n" +
            "\n" +
            "srgkpw\n" +
            "apqbxusc\n" +
            "tpmwq\n" +
            "injolypfd\n" +
            "\n" +
            "onxflkzsqwetmdrayupbijv\n" +
            "blkorzdvyxiuawgnqpmstef\n" +
            "fsnpxiueltmzovwrabyqdk\n" +
            "bfxsyekrnvdqzoutwpiagmhl\n" +
            "\n" +
            "jahltpfywcnobux\n" +
            "hcwfadpkyzms\n" +
            "oglqhpifavcwyx\n" +
            "\n" +
            "migjhyvpnf\n" +
            "ufjyqv\n" +
            "\n" +
            "txoci\n" +
            "z\n" +
            "izvugb\n" +
            "rpydhl\n" +
            "xbm\n" +
            "\n" +
            "ajlfb\n" +
            "bfl\n" +
            "jslof\n" +
            "fzrnmlqek\n" +
            "ofdl\n" +
            "\n" +
            "crbuzmjlnsoixgyatf\n" +
            "gkbasourfjcimlxtnv\n" +
            "ndmwxstgfoubrcljia\n" +
            "qmfoxlhnrubetgjsaci\n" +
            "\n" +
            "msr\n" +
            "ir\n" +
            "\n" +
            "ypv\n" +
            "vp\n" +
            "vp\n" +
            "rpv\n" +
            "pv\n" +
            "\n" +
            "jquxr\n" +
            "hngqptklaeuimrw\n" +
            "frbdvoucq\n" +
            "drusqy\n" +
            "xqdzur\n" +
            "\n" +
            "ifnuymdhesgzpjkroqwc\n" +
            "nqshkiwoyfcupmjgrezd\n" +
            "cpqmjwreogdyhuznfkis\n" +
            "pzijugdfykreocnqhswm\n" +
            "\n" +
            "wletxi\n" +
            "twlxe\n" +
            "tjewrlmx\n" +
            "sflciwxet\n" +
            "\n" +
            "cqmtspovlhxzwknijgdbya\n" +
            "jktgvsnfmobiwxplqzyc\n" +
            "oniglefctyxvbzpsqkmjw\n" +
            "\n" +
            "aqbujkmecp\n" +
            "jcakubpeqm\n" +
            "\n" +
            "ms\n" +
            "s\n" +
            "g\n" +
            "d\n" +
            "s\n" +
            "\n" +
            "ymb\n" +
            "bmy\n" +
            "tbym\n" +
            "zmby\n" +
            "zymb\n" +
            "\n" +
            "zmajf\n" +
            "afd\n" +
            "\n" +
            "saqutcgmzpvrx\n" +
            "qzumvpcraxgts\n" +
            "zcmgpquxnrsavt\n" +
            "uxztgakmcqsypvr\n" +
            "xmvqurazcptsg\n" +
            "\n" +
            "xgcnvwikzmh\n" +
            "jualdmfogexcp\n" +
            "vrixcgqmbt\n" +
            "gcxms\n" +
            "\n" +
            "hlf\n" +
            "jzeubrawvgonf\n" +
            "yqxcpkhf\n" +
            "\n" +
            "wpkbqaver\n" +
            "kwenvqrpbd\n" +
            "pswekvrqb\n" +
            "vbepwrqk\n" +
            "rkweqpvb\n" +
            "\n" +
            "r\n" +
            "ef\n" +
            "eqh\n" +
            "e\n" +
            "\n" +
            "nvzfi\n" +
            "znmev\n" +
            "ohnlvzk\n" +
            "vnezjc\n" +
            "\n" +
            "whkjfmbtausedyvqx\n" +
            "tmqxhkfsydevuwba\n" +
            "srvfbdkymwtqxiehcupa\n" +
            "lsatxumedbwfkvyhq\n" +
            "\n" +
            "aligpe\n" +
            "glpaie\n" +
            "aliepg\n" +
            "eilagp\n" +
            "\n" +
            "xvigpscledkfwjbztn\n" +
            "sgejnlvxdtbzfckpiwh\n" +
            "vlcwftebgjsndpzixk\n" +
            "swkzngbdcexifltvjp\n" +
            "\n" +
            "zrethjknvsdwf\n" +
            "qldrsgybijfhz\n" +
            "\n" +
            "tlhogxqens\n" +
            "habqtneudxljgks\n" +
            "xqtsnelhmgo\n" +
            "qlnteghxs\n" +
            "\n" +
            "bhc\n" +
            "ec\n" +
            "ch\n" +
            "jgiyc\n" +
            "\n" +
            "xzfioelc\n" +
            "ozilcexf\n" +
            "zfeoxcli\n" +
            "clefxioz\n" +
            "\n" +
            "uqjkybfsehwxzlptrni\n" +
            "caryzpjnukwlxesgtbhf\n" +
            "jzwkubtlsypqhneforx\n" +
            "xlrwkspjyufnzebht\n" +
            "\n" +
            "tvzuoab\n" +
            "bv\n" +
            "bgv\n" +
            "bv\n" +
            "\n" +
            "ltujriwpmyna\n" +
            "jtrmpw\n" +
            "mwtspjr\n" +
            "tmorwjp\n" +
            "\n" +
            "tyjsqfripxz\n" +
            "rpzxytjqsif\n" +
            "xtyrspijzfq\n" +
            "ctixjyfzrsqp\n" +
            "\n" +
            "ycjihklnd\n" +
            "ezvuqn\n" +
            "\n" +
            "chtgvuilo\n" +
            "uvgticloh\n" +
            "\n" +
            "hmgyx\n" +
            "yghlx\n" +
            "\n" +
            "oejuvpaigsrqh\n" +
            "pijsveugqroha\n" +
            "eviqopasurjgh\n" +
            "iroqaphsuevjg\n" +
            "qauzoirjghsevp\n" +
            "\n" +
            "gumpokcdtinjberaxqfz\n" +
            "xdounkjezmrpfbicqgt\n" +
            "pzfgicekuymqnrxodbjt\n" +
            "\n" +
            "npy\n" +
            "nyp\n" +
            "ypn\n" +
            "ynp\n" +
            "ypn\n" +
            "\n" +
            "xfhucsdlpveoir\n" +
            "mnzobifxtkr\n" +
            "\n" +
            "hy\n" +
            "yh\n" +
            "\n" +
            "iumnsyqgw\n" +
            "wgyismd\n" +
            "rdmgwiyhfs\n" +
            "xzgywmis\n" +
            "\n" +
            "dwfplygjx\n" +
            "vuhewxszq\n" +
            "bxnrmocki\n" +
            "xtyea\n" +
            "\n" +
            "ouyqrtczxwj\n" +
            "xqtyujwocrzb\n" +
            "qjxuyrotkwcz\n" +
            "\n" +
            "qjtcyaoexnvl\n" +
            "nxtaqkjloce\n" +
            "tzcongqajpxle\n" +
            "\n" +
            "olubpxmfdayik\n" +
            "leqomjitfbay\n" +
            "\n" +
            "lygezhjmbi\n" +
            "clvphtkud\n" +
            "\n" +
            "vp\n" +
            "pv\n" +
            "pvkfw\n" +
            "pmv\n" +
            "\n" +
            "rpsclgeuhmkja\n" +
            "mcgypeuswakhio\n" +
            "\n" +
            "ajdpyugzbcswtei\n" +
            "pcadiemunsbgw\n" +
            "ludvapgecqsfbwi\n" +
            "elsugdcfnhbipwa\n" +
            "\n" +
            "vfzoqrbgjycuenwlxdts\n" +
            "fgdnclwtoyxqvuesjrzb\n" +
            "ejatdrohipbxucyvnwzfsqgl\n" +
            "utsloejxznvwybdrfgcq\n" +
            "\n" +
            "vwkaomqupbitzrh\n" +
            "pvawbkoztumqhr\n" +
            "\n" +
            "ijbcxau\n" +
            "cijuoea\n" +
            "cjifuyqa\n" +
            "cubtxaji\n" +
            "jxcaiu\n" +
            "\n" +
            "zsankwocrhb\n" +
            "dchzrbkmaswon\n" +
            "\n" +
            "jdcfne\n" +
            "nfedjc\n" +
            "qeczfjn\n" +
            "fcejqn\n" +
            "jnefvc\n" +
            "\n" +
            "vpzmjnb\n" +
            "zbvjqdys\n" +
            "zbxpdjmial\n" +
            "ktouerbjgwz\n" +
            "jsbzhc\n" +
            "\n" +
            "zbsi\n" +
            "zisb\n" +
            "\n" +
            "txvngrdas\n" +
            "vadsrgtx\n" +
            "\n" +
            "qgnvriol\n" +
            "\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "f\n" +
            "\n" +
            "mvuywsiaqcl\n" +
            "nqavfwhsicz\n" +
            "\n" +
            "yuomdcgnvwhakel\n" +
            "auwkhgoycmlevn\n" +
            "\n" +
            "icagyksq\n" +
            "crsahngi\n" +
            "\n" +
            "vb\n" +
            "ftlgxroupjyis\n" +
            "cvh\n" +
            "\n" +
            "vcimkpuafwqbryogjxdt\n" +
            "mxyftdriubhawgjcvpkq\n" +
            "rybptdfhaoxkgvmjuciqw\n" +
            "idxrkpygcwvltaefmbqju\n" +
            "trmjbiqpnyhvscwxafukgd\n" +
            "\n" +
            "esbdajqhvl\n" +
            "jdqlszev\n" +
            "foedswyvlunq\n" +
            "ixevsdtblmq\n" +
            "rvetlqsdk\n" +
            "\n" +
            "islfcy\n" +
            "yif\n" +
            "bify\n" +
            "ioymf\n" +
            "\n" +
            "hrcqst\n" +
            "pecr\n" +
            "\n" +
            "gwd\n" +
            "wdg\n" +
            "dgw\n" +
            "dgw\n" +
            "\n" +
            "ksyqndmahzgxejfp\n" +
            "sexhgkfzdapyqmjn\n" +
            "dejzykngpamhfqxs\n" +
            "\n" +
            "fmohepc\n" +
            "pucg\n" +
            "cp\n" +
            "\n" +
            "xvdmorgbsnawjlecztykpif\n" +
            "rsmwdvfplkencbzaotgjix\n" +
            "\n" +
            "wjhkg\n" +
            "gbkh\n" +
            "dklegsrmhy\n" +
            "hukgw\n" +
            "\n" +
            "flwu\n" +
            "lnzckx\n" +
            "vetd\n" +
            "myj\n" +
            "xwcp\n" +
            "\n" +
            "vjhnftpyr\n" +
            "nfhjvyrpt\n" +
            "\n" +
            "lne\n" +
            "nel\n" +
            "nle\n" +
            "\n" +
            "hgqjcse\n" +
            "chfja\n" +
            "jqcus\n" +
            "kozlctmiy\n" +
            "\n" +
            "h\n" +
            "h\n" +
            "h\n" +
            "h\n" +
            "h\n" +
            "\n" +
            "lwco\n" +
            "wloc\n" +
            "tlkuwco\n" +
            "lwoc\n" +
            "\n" +
            "egzxalry\n" +
            "zyxaklpge\n" +
            "zlwergaxy\n" +
            "\n" +
            "nghrpie\n" +
            "nqz\n" +
            "au\n" +
            "ytcdsfw\n" +
            "lbj\n" +
            "\n" +
            "jkcetobxnsyqwfdzuglv\n" +
            "gsnwvmzjxiteryacp\n" +
            "njcshegytvzxw\n" +
            "\n" +
            "qtsf\n" +
            "st\n" +
            "ts\n" +
            "ts\n" +
            "tps\n" +
            "\n" +
            "ckmnriay\n" +
            "sytrcng\n" +
            "ncywrg\n" +
            "ncygr\n" +
            "\n" +
            "rcnyivhla\n" +
            "ebgfdotjuks\n" +
            "\n" +
            "tfjcihobxywuvpezarkg\n" +
            "hckgoruvbxzenjipaywft\n" +
            "fwhtyrvebajgpkcuxoiz\n" +
            "oaruytpwzikbfhjxevgc\n" +
            "\n" +
            "oaxzdr\n" +
            "dopg\n" +
            "opzak\n" +
            "woqg\n" +
            "notveuy\n" +
            "\n" +
            "l\n" +
            "l\n" +
            "l\n" +
            "qn\n" +
            "m\n" +
            "\n" +
            "dvjuhlfmectponaxwyib\n" +
            "yfaltvohpnquirmzjdcxsb\n" +
            "\n" +
            "ib\n" +
            "bil\n" +
            "ib\n" +
            "bi\n" +
            "\n" +
            "sd\n" +
            "lo\n" +
            "\n" +
            "s\n" +
            "wsvef\n" +
            "va\n" +
            "jwvf\n" +
            "rdho\n" +
            "\n" +
            "or\n" +
            "lor\n" +
            "kro\n" +
            "\n" +
            "ze\n" +
            "e\n" +
            "e\n" +
            "\n" +
            "teh\n" +
            "ef\n" +
            "ek\n" +
            "fe\n" +
            "\n" +
            "dfbzgqpsk\n" +
            "pzgfaydsuxq\n" +
            "pgfqdsz\n" +
            "kzrfgqsdwp\n" +
            "\n" +
            "rxqgndcawfb\n" +
            "loyuzbmejivkhs\n" +
            "\n" +
            "jilybertvwkqcma\n" +
            "nuelmho\n" +
            "ledhomnuz\n" +
            "esfml\n" +
            "gxzpelm\n" +
            "\n" +
            "mikrjtbophlqduwsexvcy\n" +
            "mbrqlycjvskdwithuopex\n" +
            "qlwrcduykbmxsovijthep\n" +
            "xevmqplwtjyckbouirhds\n" +
            "bmytdrsxvupciloewqjkh\n" +
            "\n" +
            "wrnkojbmtzvchulxaisepyfdq\n" +
            "xicryqvwkumtozjdhsflegpabn\n" +
            "\n" +
            "yjxpwakhd\n" +
            "klhj\n" +
            "kjih\n" +
            "nshrgujk\n" +
            "skjhm\n" +
            "\n" +
            "fasz\n" +
            "aef\n" +
            "gmqipcfanvt\n" +
            "hsafl\n" +
            "\n" +
            "m\n" +
            "m\n" +
            "m\n" +
            "m\n" +
            "\n" +
            "ksyargzucfq\n" +
            "lyvjrmapbhqwt\n" +
            "\n" +
            "b\n" +
            "b\n" +
            "by\n" +
            "b\n" +
            "\n" +
            "d\n" +
            "dx\n" +
            "\n" +
            "lqdmrovwifbhpkg\n" +
            "dqvofhgzwipkmlsrbn\n" +
            "ihmvkdqbroflgpw\n" +
            "bghqvfipwodlkrm\n" +
            "\n" +
            "qzuabnldjsf\n" +
            "nabfzldjq\n" +
            "\n" +
            "ihkpj\n" +
            "skhj\n" +
            "khj\n" +
            "\n" +
            "pfhzgidaoumyclqwjb\n" +
            "oubaqdmhlzgjfcwyip\n" +
            "maqwihopcbdlzyfujg\n" +
            "aydlupjizwhofcbgmq\n" +
            "\n" +
            "dcifuhzpj\n" +
            "udizhcfj\n" +
            "uzcrijdhmf\n" +
            "uhfdcjize\n" +
            "dxbjhzaifuc\n" +
            "\n" +
            "mijthslvq\n" +
            "vslmjqhi\n" +
            "\n" +
            "yilmjrbsaugeqv\n" +
            "sokhewyczmgufabjv\n" +
            "maxbtsguvyejdlp\n" +
            "\n" +
            "bdysxeouwcn\n" +
            "otszxpnm\n" +
            "wbsxonkr\n" +
            "\n" +
            "btwjys\n" +
            "bjy\n" +
            "jby\n" +
            "bjy\n" +
            "\n" +
            "elobcuyqvps\n" +
            "ubeloqvyspc\n" +
            "elvcypobusq\n" +
            "qbcsuyeplov\n" +
            "\n" +
            "zshbqdmcxntwokevlpjugr\n" +
            "lubzdvwrksnhqcptmgyexjo\n" +
            "\n" +
            "csmyezwqxdpfh\n" +
            "zexmdwhcqsyfp\n" +
            "fdqeysphczxwm\n" +
            "\n" +
            "wx\n" +
            "x\n" +
            "x\n" +
            "\n" +
            "hmudcwtoix\n" +
            "duitheoxcmw\n" +
            "xeomwhtiucd\n" +
            "xmthuoiwdfc\n" +
            "\n" +
            "qgh\n" +
            "xburedysok\n" +
            "izaqc\n" +
            "vac\n" +
            "\n" +
            "c\n" +
            "xd\n" +
            "y\n" +
            "\n" +
            "bcqxzv\n" +
            "czxvb\n" +
            "xcdv\n" +
            "\n" +
            "rstdhfvyupaqnilgkx\n" +
            "thmdrvqkgyxpcewlafu\n" +
            "xkvfgpdtahinlsyquzr\n" +
            "\n" +
            "ionzfdqwacl\n" +
            "aliwfzcnodq\n" +
            "ysdoijcnpqalfwuzr\n" +
            "dialwcqofezn\n" +
            "lqwfncaoeizd\n" +
            "\n" +
            "vjnzhsyokprdwqt\n" +
            "slufncexiadgw\n" +
            "\n" +
            "lmanxbzrvkgju\n" +
            "cotlneyfp\n" +
            "\n" +
            "ehcxwrapivns\n" +
            "nvewjcaspixr\n" +
            "ecpdkqxvastmn\n" +
            "\n" +
            "okgbcwvytiznshexu\n" +
            "kwyszldpbuthoxnj\n" +
            "kotjwysnuzxhb\n" +
            "juzbwshqatknxomy\n" +
            "krzthuxqynfoswb\n" +
            "\n" +
            "rjfbkgapzqiwnecoh\n" +
            "ohjnfzrabwcgqipek\n" +
            "bgmzawokijpnqhfcre\n" +
            "vwherzicopkqbanjufg\n" +
            "\n" +
            "qrwxpijsu\n" +
            "apuwbfirqjs\n" +
            "\n" +
            "rgynxak\n" +
            "uaxpirf\n" +
            "\n" +
            "sf\n" +
            "f\n" +
            "uf\n" +
            "ihxfzdy\n" +
            "\n" +
            "dvcrwsbpziytjqhnuoa\n" +
            "ehgudqsyzkbrnpt\n" +
            "sptdxznyeuhrqb\n" +
            "uqzbhfynsrtdp\n" +
            "srpymhztqbdunl\n" +
            "\n" +
            "rqly\n" +
            "dlaxpwrji\n" +
            "rbljwh\n" +
            "\n" +
            "grascdfzlpxoeqvtyn\n" +
            "xcnfwvryspeukbodzlatg\n" +
            "\n" +
            "oqlucpvdizwh\n" +
            "trakqib\n" +
            "agitjq\n" +
            "\n" +
            "yslaopvredmzcjnighqtfk\n" +
            "ohgqmkatyrledjnifspzc\n" +
            "\n" +
            "xwliz\n" +
            "czvfiqxw\n" +
            "gyswmhb\n" +
            "\n" +
            "fpndrua\n" +
            "aurfp\n" +
            "rpuaf\n" +
            "raufp\n" +
            "\n" +
            "eukjozdbqcxpyl\n" +
            "qyfmkxzboulcpejd\n" +
            "zlquxdybcepjko\n" +
            "\n" +
            "dlgxuchpnmosfr\n" +
            "dxcoshzfguykpvm\n" +
            "awgdpubxiefsohqj\n" +
            "\n" +
            "abop\n" +
            "abvpo\n" +
            "napobc\n" +
            "vapob\n" +
            "\n" +
            "wryqzk\n" +
            "kwqyc\n" +
            "wyzqkr\n" +
            "ykwqzo\n" +
            "ywkqr\n" +
            "\n" +
            "jbk\n" +
            "tkbj\n" +
            "bjkcn\n" +
            "bjk\n" +
            "jkb\n" +
            "\n" +
            "fagxpiolshctke\n" +
            "xtiochpabflsk\n" +
            "\n" +
            "fqdteprviumho\n" +
            "meitwhforpduqv\n" +
            "utfrhempwodviq\n" +
            "nehmyipftrqdlucov\n" +
            "\n" +
            "anqedwylpuv\n" +
            "edoqpufvwzx\n" +
            "tiuqvjhcrpewkmd\n" +
            "psvudgeqw\n" +
            "gdwulbpvqze\n" +
            "\n" +
            "znugjimbptvefqhxr\n" +
            "suxktycoplwe\n" +
            "\n" +
            "qtludyrb\n" +
            "yqrludv\n" +
            "lqdyur\n" +
            "ldqryu\n" +
            "lurkzqyvad\n" +
            "\n" +
            "cwmikuhtgole\n" +
            "tzghimclkue\n" +
            "igtxkcpsmlydhe\n" +
            "khtglcqmuie\n" +
            "imhwecgltk\n" +
            "\n" +
            "pschkw\n" +
            "schnwpultqk\n" +
            "iwzohyej\n" +
            "\n" +
            "dwxbfsq\n" +
            "dswfbqx\n" +
            "\n" +
            "tpby\n" +
            "ptq\n" +
            "qpt\n" +
            "tp\n" +
            "\n" +
            "nqtocmfdjpskriev\n" +
            "agvctwbfxkyj\n" +
            "\n" +
            "kqdewilc\n" +
            "qweluikd\n" +
            "\n" +
            "qbyv\n" +
            "vb\n" +
            "\n" +
            "k\n" +
            "jmp\n" +
            "\n" +
            "lvnqfrdctwzk\n" +
            "xtljgevz\n" +
            "tusihlzv\n" +
            "\n" +
            "vrtojs\n" +
            "rvtzosj\n" +
            "jrcqvsutohwl\n" +
            "zvpsjtgoar\n" +
            "\n" +
            "wkh\n" +
            "wh\n" +
            "hbtl\n" +
            "qh\n" +
            "\n" +
            "jzcdykoafitepbxlqvmns\n" +
            "yqcpzvksoinjlebfdatxm\n" +
            "\n" +
            "rvmjscznedib\n" +
            "smineqdwcjvrz\n" +
            "duejsmrncviz\n" +
            "idrmvcsezlnjf\n" +
            "\n" +
            "qognsitfwkcmvd\n" +
            "qbonaiuktrc\n" +
            "ctkiyqnou\n" +
            "iptrcqjkhzoaxn\n" +
            "\n" +
            "msjqvb\n" +
            "wxfpej\n" +
            "\n" +
            "zgdmaphfuiols\n" +
            "oemgjuxavhcsfzdilp\n" +
            "gopdafmiulshz\n" +
            "zaphsolgumftid\n" +
            "fdgmahupzsoil\n" +
            "\n" +
            "svdmfou\n" +
            "uofmsdv\n" +
            "fuvsodm\n" +
            "uvmodfs\n" +
            "vsoumdf\n" +
            "\n" +
            "pn\n" +
            "gn\n" +
            "np\n" +
            "hsnc\n" +
            "nem\n" +
            "\n" +
            "ondycsxijkhztmb\n" +
            "sdtmkibxjyu\n" +
            "\n" +
            "cfdbyz\n" +
            "dbcfyz\n" +
            "ocfbzyd\n" +
            "bfzdyc\n" +
            "fcbydz\n" +
            "\n" +
            "rycjvanzo\n" +
            "qzecro\n" +
            "zrqoc\n" +
            "\n" +
            "iytqmcheg\n" +
            "gyiectmh\n" +
            "\n" +
            "idcpxfhmwbutsogkazl\n" +
            "iwoydxlchsezubtkgpma\n" +
            "fcwtdoulsphxmibkazg\n" +
            "woshuclmdzibaxpgkt\n" +
            "\n" +
            "lvpfdtgw\n" +
            "jysqnxkozermwc\n" +
            "aywockbuh\n" +
            "\n" +
            "hlgrnxofckptmqvaebsdwi\n" +
            "lhqtonswkdmvrcibfxape\n" +
            "wqimranhsepdotcfbxlvk\n" +
            "ksxwcidfaoqlbrvenhtpm\n" +
            "dncheprotawksmxflvbiq\n" +
            "\n" +
            "mkcyzpfseqg\n" +
            "yqgmkczvt\n" +
            "zbiqoynxkrjd\n" +
            "\n" +
            "qalxdcz\n" +
            "wuchrlszbepm\n" +
            "\n" +
            "tisl\n" +
            "tjoycs\n" +
            "\n" +
            "uixno\n" +
            "zicsuorn\n" +
            "xuqiokn\n" +
            "\n" +
            "qadwnkvfzltpib\n" +
            "ctehovpradslgxujwnmbfiq\n" +
            "\n" +
            "lnbzhdvqucg\n" +
            "udvzgqlcbhn\n" +
            "zcvhlqndgub\n" +
            "\n" +
            "dnkeso\n" +
            "enskdo\n" +
            "sneokd\n" +
            "oknsde\n" +
            "dekson\n" +
            "\n" +
            "aqxyozpubvjgcr\n" +
            "ybpjqrcoagxuzv\n" +
            "yrajbvpogcuqzx\n" +
            "ubarxgvqyjpzoc\n" +
            "xqupgyrovzcjba\n" +
            "\n" +
            "galcpxukjvdfz\n" +
            "jcvgulafdxpzk\n" +
            "gchxzuajvlkpdf\n" +
            "\n" +
            "pds\n" +
            "euwsvd\n" +
            "dsf\n" +
            "\n" +
            "phvzus\n" +
            "rhlztp\n" +
            "phzdla\n" +
            "\n" +
            "rfpbcyd\n" +
            "rbdycpf\n" +
            "\n" +
            "brwpvt\n" +
            "spvtrjb\n" +
            "vytpbr\n" +
            "tbsrvwp\n" +
            "rvtpb\n" +
            "\n" +
            "efmkb\n" +
            "bemkf\n" +
            "bekmf\n" +
            "temfkb\n" +
            "\n" +
            "jyzinpl\n" +
            "efxqapwo\n" +
            "rzup\n" +
            "dpcr\n" +
            "\n" +
            "bawpqhnvmtuxsflizck\n" +
            "avqcthmkpifswzlnxu\n" +
            "slmqcpnxivzahkutwf\n" +
            "\n" +
            "zsakf\n" +
            "skfeza\n" +
            "\n" +
            "neqbzcajpw\n" +
            "onzqsaxhcbwljdm\n" +
            "\n" +
            "do\n" +
            "do\n" +
            "od\n" +
            "od\n" +
            "\n" +
            "rieubqwd\n" +
            "cqrupedvitb\n" +
            "edbqirun\n" +
            "\n" +
            "hvrpjfwud\n" +
            "zpauyi\n" +
            "kbxmeupq\n" +
            "uptwfhgzaj\n" +
            "\n" +
            "vkqf\n" +
            "fhnpyx\n" +
            "gawucsozmdi\n" +
            "tbrpnlekj\n" +
            "\n" +
            "neriadovyhuzkqgc\n" +
            "rqflhpywekobzstjumcn\n" +
            "\n" +
            "bvzumtnorcqhyilgwe\n" +
            "tvnioyzlwmerhgbuq\n" +
            "wylinhomzvetrbuqgdc\n" +
            "ghbltunyeopfrqizmwavx\n" +
            "\n" +
            "jvrieqgfklch\n" +
            "pjndlghruvif\n" +
            "\n" +
            "xbwvzikjtnhfayp\n" +
            "tgcadrqjxuel\n" +
            "\n" +
            "lbxsjvamqwdfutrck\n" +
            "bwrxdaqzuftlmvk\n" +
            "zbtmakqxdfpruwlv\n" +
            "\n" +
            "jrisgax\n" +
            "gries\n" +
            "rigts\n" +
            "girjspe\n" +
            "pasieghr\n" +
            "\n" +
            "reqwbsjzlghkv\n" +
            "gkmvstdcaroqbzjp\n" +
            "qhrvngfjzsblku\n" +
            "\n" +
            "vtilu\n" +
            "i\n" +
            "i\n" +
            "\n" +
            "cmizk\n" +
            "kmcdwi\n" +
            "tokljcmiv\n" +
            "\n" +
            "gcmxdqoysrjhzvunkbtpwfi\n" +
            "rsvhxmjgbdupqotnywkcifz\n" +
            "byczhwkrnmujqoidfpstxgv\n" +
            "romdtyjgwbcpihafslznxqkvu\n" +
            "\n" +
            "kcx\n" +
            "wfsoxa\n" +
            "rcxk\n" +
            "xecl\n" +
            "\n" +
            "xhljmt\n" +
            "lheratmxj\n" +
            "fhmxtcwlb\n" +
            "xhlmaritg\n" +
            "thxmalo\n" +
            "\n" +
            "usfhzlidpmxvonr\n" +
            "luvxhfdcmrpn\n" +
            "xpfldmuhvrn\n" +
            "lumvrnedxfphk\n" +
            "lpvdnfurmxhk\n" +
            "\n" +
            "ukqco\n" +
            "bg\n" +
            "d\n" +
            "x\n" +
            "\n" +
            "wshkqpojltbyexrvfcmaiugd\n" +
            "ptxsveguqfjdimboarwclhky\n" +
            "figabshrwotdqjepmlxkyvcu\n" +
            "imgseacrdxfkyptwhvoblujq\n" +
            "wflyahpcgbrsmvkitejxoqud\n" +
            "\n" +
            "cdfihsmoy\n" +
            "smieho\n" +
            "mhsoi\n" +
            "oenshami\n" +
            "ozlhswmi\n" +
            "\n" +
            "pefjcrt\n" +
            "vdfzpwrtc\n" +
            "ptegcbfr\n" +
            "\n" +
            "uet\n" +
            "uet\n" +
            "eut\n" +
            "\n" +
            "ubyk\n" +
            "ukygtrole\n" +
            "jukzxqhvy\n" +
            "eumldfkyos\n" +
            "knaiuywrm\n" +
            "\n" +
            "ncjzgqof\n" +
            "qafcjnzog\n" +
            "zojngqfc\n" +
            "\n" +
            "uxkryjwflco\n" +
            "psolcaquvwkdnizre\n" +
            "\n" +
            "linoudwypsgbvmx\n" +
            "wugpsidobmnryv\n" +
            "udynmoswgb\n" +
            "kydhcbnozusmegwt\n" +
            "sygbrmudwnafo\n" +
            "\n" +
            "sfkatdxbyqezirv\n" +
            "skvtiarxeybzf\n" +
            "viyzrlampbxtskfe\n" +
            "vyqazixrftsebk\n" +
            "\n" +
            "bjwqhkryuz\n" +
            "zmwkyuqhjrb\n" +
            "qjuwrzhybsk\n" +
            "hyzwujqbkr\n" +
            "\n" +
            "wjahb\n" +
            "jywahb\n" +
            "jbawh\n" +
            "jwhba\n" +
            "\n" +
            "aetucrzpvn\n" +
            "esznbtkoy\n" +
            "eztdn\n" +
            "zonte\n" +
            "\n" +
            "dkpu\n" +
            "mpqcixu\n" +
            "pwu\n" +
            "psu\n" +
            "pudkhyv\n" +
            "\n" +
            "ydtaink\n" +
            "atndubyk\n" +
            "ocytkdain\n" +
            "wnvgzytadkps\n" +
            "\n" +
            "mtne\n" +
            "mten\n" +
            "netm\n" +
            "netm\n" +
            "\n" +
            "l\n" +
            "lz\n" +
            "l\n" +
            "l\n" +
            "l\n" +
            "\n" +
            "wfu\n" +
            "wfu\n" +
            "uwf\n" +
            "uwf\n" +
            "\n" +
            "wcxsiaokerlumjnqyfvhtbgd\n" +
            "abrlxsfzqjuwnotehgmdkcyv\n" +
            "\n" +
            "kate\n" +
            "aekt\n" +
            "akte\n" +
            "teak\n" +
            "\n" +
            "spxqizdhbuokw\n" +
            "pwdxibkuzsqohr\n" +
            "qkszwvaulbpdthoig\n" +
            "ouwqdkzypbhis\n" +
            "\n" +
            "xlskunagot\n" +
            "onxagbulsem\n" +
            "olnsagux\n" +
            "\n" +
            "mhrst\n" +
            "hm\n" +
            "hm\n" +
            "hknuimeg\n" +
            "\n" +
            "pzwtsrfhcmqidnaeybgxkluvoj\n" +
            "keugsjaimzwbxqcvndytfhlpor\n" +
            "\n" +
            "gezfhs\n" +
            "nsyftgje\n" +
            "csifykhegj\n" +
            "fdrgmqvse\n" +
            "\n" +
            "eqagibxdlst\n" +
            "gdisebqlxat\n" +
            "eogtidqaslbx\n" +
            "tdbqslaigxe\n" +
            "eltabiqxsdg\n" +
            "\n" +
            "hopcmlyfka\n" +
            "zleytsfdpcgbn\n" +
            "\n" +
            "iq\n" +
            "qm\n" +
            "ajngr\n" +
            "\n" +
            "jgnh\n" +
            "pdqzyblwuh\n" +
            "tovghj\n" +
            "\n" +
            "jsztoebhflkrncuygi\n" +
            "epzghnfcoljutisryk\n" +
            "ugnysrzftjieholckm\n" +
            "kyeuglztrshjnbfico\n" +
            "\n" +
            "q\n" +
            "q\n" +
            "q\n" +
            "q\n" +
            "\n" +
            "zch\n" +
            "zhc\n" +
            "ch\n" +
            "cdgh\n" +
            "hcw\n" +
            "\n" +
            "nubdmx\n" +
            "xunbd\n" +
            "dxunb\n" +
            "wbxund\n" +
            "udnbex\n" +
            "\n" +
            "dfcauy\n" +
            "afdcuy\n" +
            "dfcuya\n" +
            "uafcdyn\n" +
            "fudyac\n" +
            "\n" +
            "cdgkzushqaevntrop\n" +
            "ndhzqxgksrpotcaev\n" +
            "qetkhzodnsrcgvap\n" +
            "epcvrnokadgzhstq\n" +
            "nozqsrhcegpavdkt\n" +
            "\n" +
            "wbpaec\n" +
            "jmfyir\n" +
            "\n" +
            "wozuxcnegrjikhy\n" +
            "eritoghwxluynkjzc\n" +
            "okrecihjuwxznbgy\n" +
            "nuwirjxkezyghoc\n" +
            "\n" +
            "g\n" +
            "q\n" +
            "r\n" +
            "\n" +
            "jdr\n" +
            "rj\n" +
            "rj\n" +
            "\n" +
            "ogs\n" +
            "szgo\n" +
            "osyugw\n" +
            "sogj\n" +
            "ogs\n" +
            "\n" +
            "ixnlzuvyar\n" +
            "ryznvumlqfexi\n" +
            "icylvxzrnu\n" +
            "lurxhyvzni\n" +
            "nixylzvrut\n" +
            "\n" +
            "xv\n" +
            "xs\n" +
            "x\n" +
            "kfwax\n" +
            "hxu\n" +
            "\n" +
            "dkjohmvtxscaqpyzbie\n" +
            "bdvtjzyhoaecmxpiqks\n" +
            "eyhsxtdoazqvcbpmikj\n" +
            "oevbpqstmxchykizdja\n" +
            "mbvjkyzihcsqepadxot\n" +
            "\n" +
            "vkqgipbhsmczdaery\n" +
            "ckomvhixysdq\n" +
            "cvixystlohmkqd\n" +
            "noyqmhdfuvkcis\n" +
            "\n" +
            "jeqcx\n" +
            "xjqec\n" +
            "jceqx\n" +
            "qcjex\n" +
            "\n" +
            "okncyha\n" +
            "kha\n" +
            "wdqkamrhi\n" +
            "\n" +
            "uajtdcwglpxf\n" +
            "ldxgwjauscp\n" +
            "avciwljdyxupg\n" +
            "lgctupaxwjd\n" +
            "zjblqcxwkrgdanup\n" +
            "\n" +
            "ogpcjvltkizyrubnshf\n" +
            "xrpukdzmcsqlnofejigtvbh\n" +
            "nhvztyfbsuicjlrkopg\n" +
            "\n" +
            "rklv\n" +
            "lnvr\n" +
            "vrsle\n" +
            "\n" +
            "tdoeb\n" +
            "toebz\n" +
            "jbot\n" +
            "\n" +
            "ahntqkrwvxc\n" +
            "htray\n" +
            "tehar\n" +
            "\n" +
            "xbis\n" +
            "q\n" +
            "p\n" +
            "\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "\n" +
            "svpnoi\n" +
            "vsnroip\n" +
            "\n" +
            "rkdetpah\n" +
            "hpdmjrekao\n" +
            "ybzcrhkguew\n" +
            "\n" +
            "ha\n" +
            "qkj\n" +
            "vzcjq\n" +
            "\n" +
            "ubjqtpfxalnv\n" +
            "uftvrxjqpbnla\n" +
            "tbunjpvqfxalh\n" +
            "\n" +
            "izesvwkmyohlqr\n" +
            "jhtqnmyiawpskz\n" +
            "\n" +
            "jdoqhwbftxpavygze\n" +
            "zydthexqgwpkaovnfj\n" +
            "cdsvzfxwtigjamryhqep\n" +
            "\n" +
            "srvdcubotnwkx\n" +
            "dmhpqyzikcslargnj\n" +
            "\n" +
            "tcmoi\n" +
            "ptqeci\n" +
            "buvtic\n" +
            "\n" +
            "kisteoqyjapdrcgfx\n" +
            "sqdxjckrfoytap\n" +
            "ztrdcxsayfkqjop\n" +
            "rjxfkpdaqysozctm\n" +
            "fyctdxsrkaojqpu\n" +
            "\n" +
            "chtzwxr\n" +
            "ozcrsthux\n" +
            "\n" +
            "oqahrvuinct\n" +
            "uavtnforke\n" +
            "ounartv\n" +
            "akunvrot\n" +
            "uonvftmar\n" +
            "\n" +
            "hveqfbrwkdosnay\n" +
            "zofutwkxmpgnljic\n" +
            "\n" +
            "sexkhbfwvagzjq\n" +
            "hryamtnf\n" +
            "phacfo\n" +
            "\n" +
            "yzdbglajf\n" +
            "lybfajgzid\n" +
            "ldjagfbyz\n" +
            "djlyzfbga\n" +
            "lgyjzfabd\n" +
            "\n" +
            "mk\n" +
            "km\n" +
            "mk\n" +
            "mk\n" +
            "\n" +
            "vupse\n" +
            "utvf\n" +
            "veu\n" +
            "noubvi\n" +
            "vslpu\n" +
            "\n" +
            "gxcz\n" +
            "xgcz\n" +
            "zxgc\n" +
            "cgxz\n" +
            "\n" +
            "xsgkotfqldj\n" +
            "ltwmgjofxdsk\n" +
            "\n" +
            "sptmvzkdoxwqrefgn\n" +
            "zwa\n" +
            "ybwjzuchl\n" +
            "\n" +
            "jqdxzbhsctn\n" +
            "ocsat\n" +
            "tokewcs\n" +
            "usktc\n" +
            "\n" +
            "hqctliu\n" +
            "ilchptqu\n" +
            "quchitlj\n" +
            "lcuqtih\n" +
            "ipbqctulh\n" +
            "\n" +
            "wgihvaqrxpczsmflydjuket\n" +
            "mclinzpejdgtsfwqhyxkrvua\n" +
            "\n" +
            "sdgycjfmukezpx\n" +
            "bvwzqrmnti\n" +
            "\n" +
            "xoizphtv\n" +
            "mfzxhitopvag\n" +
            "hzipoxtv\n" +
            "rdtxiopvhz\n" +
            "hnvopxzti\n" +
            "\n" +
            "nluidsozya\n" +
            "sxcqziol\n" +
            "\n" +
            "vf\n" +
            "vf\n" +
            "fv\n" +
            "fv\n" +
            "vf\n" +
            "\n" +
            "x\n" +
            "x\n" +
            "mdtxr\n" +
            "\n" +
            "cspzldibokwq\n" +
            "bnktcpxzwlmeijqvd\n" +
            "pqkcyzhwbild\n" +
            "\n" +
            "zmdrvaxgtiq\n" +
            "jydtqgcm\n" +
            "dqgtxlm\n" +
            "fnxtegsmqrad\n" +
            "gkqmdtv\n" +
            "\n" +
            "zwulxhevg\n" +
            "jtwpxvdczlsh\n" +
            "znxlvhw\n" +
            "laozqhwrvgx\n" +
            "xmlvhfizw\n" +
            "\n" +
            "ixjseyvhfcupkz\n" +
            "jifehpsczxyvu\n" +
            "ixhvyweujozsmpfc\n" +
            "wpfskxljyceiuzhv\n" +
            "gydqfcphztjesirxuv\n" +
            "\n" +
            "bdolgwcua\n" +
            "cogbawu\n" +
            "ugabwco\n" +
            "obtcwagu\n" +
            "wcbuoga\n" +
            "\n" +
            "txjldzfwhbqcspemvgkiyn\n" +
            "kmdswhijztqfyclebvnpgx\n" +
            "szydcbewfnmvpxhijtqklg\n" +
            "\n" +
            "jfxehga\n" +
            "aoxhj\n" +
            "vuaozhjqxi\n" +
            "hxjqvia\n" +
            "\n" +
            "cyknepoazhsml\n" +
            "dhoecksznaylp\n" +
            "uktqnwrhivasbcxlepy\n" +
            "yshcfelankp\n" +
            "\n" +
            "mgbwxcvkrl\n" +
            "tzoauif\n" +
            "qpjntdoysueh\n" +
            "\n" +
            "n\n" +
            "n\n" +
            "\n" +
            "briatspxkzdwue\n" +
            "abdgifsljzuo\n" +
            "\n" +
            "vklpca\n" +
            "lkavpc\n" +
            "\n" +
            "lfxguyd\n" +
            "dzfuex\n" +
            "\n" +
            "zqxod\n" +
            "qxd\n" +
            "qdx\n" +
            "xhqude\n" +
            "\n" +
            "ovigcernldjwzy\n" +
            "idegzjvrwlyn\n" +
            "\n" +
            "cb\n" +
            "bc\n" +
            "rbcxdh\n" +
            "bc\n" +
            "\n" +
            "givtqeysrcjfzumod\n" +
            "isrgtyjavfwcoekdzmuq\n" +
            "zdgtmescqrvyiujfo\n" +
            "ogumbvzcdejyrtsiqf\n" +
            "qdfjsoetuvrymzcig\n" +
            "\n" +
            "fwruktphdzan\n" +
            "zkfpnrthwaud\n" +
            "unrhpzwtdafk\n" +
            "\n" +
            "odlubiyrqzfevnjpakwtgmx\n" +
            "lrsdjkauwbvztfymqginoxpe\n" +
            "omeqnvadjubzwkxritgyplf\n" +
            "fjzywpmkeaotldvguqbnixr\n" +
            "\n" +
            "emayzjxi\n" +
            "axzreyckm\n" +
            "\n" +
            "lduhiqwpjrnkto\n" +
            "ntcrjqdkwphloi\n" +
            "thjdwnklqirpo\n" +
            "tqpdwjilhoknr\n" +
            "\n" +
            "vi\n" +
            "iv\n" +
            "vir\n" +
            "\n" +
            "xoetdfmrbvl\n" +
            "dfebtomilx\n" +
            "fbltmdexo\n" +
            "\n" +
            "hmcuklq\n" +
            "lusqkch\n" +
            "iqjpulckh\n" +
            "suchkql\n" +
            "\n" +
            "gu\n" +
            "gu\n" +
            "gu\n" +
            "ugn\n" +
            "gu\n" +
            "\n" +
            "lvtfiecgrzxhm\n" +
            "tircajhne\n" +
            "\n" +
            "fm\n" +
            "if\n" +
            "\n" +
            "subio\n" +
            "buosi\n" +
            "boisu\n" +
            "busoi\n" +
            "\n" +
            "uwkhxabg\n" +
            "hofrviyqz\n" +
            "wkuhs\n" +
            "\n" +
            "zoswictnpdvjegqymbfura\n" +
            "cmrnqyupavzbfjegidtso\n" +
            "xpycanfhjrulqzvmtdbsegoi\n" +
            "iqdrfstyjgabzenpvckomu\n" +
            "\n" +
            "kzardg\n" +
            "dkzgura\n" +
            "zdagrk\n" +
            "gdrakz\n";

    @Test
    public void test1() throws Exception {
        BufferedReader reader = new BufferedReader(new StringReader(input2));
        String line = null;
        List<List<Set<Character>>> s1 = new LinkedList<>();
        List<Set<Character>> currentList = new LinkedList<>();
        while ((line = reader.readLine()) != null) {
            if (line.equals("")) {
                s1.add(currentList);
                currentList = new LinkedList<>();
                continue;
            }
            Set<Character> person = new HashSet<>();
            currentList.add(person);
            for (char c : line.toCharArray()) {
                person.add(c);
            }
        }
        s1.add(currentList);

        int c = 0;
        for (List<Set<Character>> sets : s1) {
            Set<Character> all = new HashSet<>();
            for (Set<Character> set : sets) {
                all.addAll(set);
            }
            c += all.size();
        }

        System.out.println(c);
    }

    @Test
    public void test2() throws Exception {
        BufferedReader reader = new BufferedReader(new StringReader(input2));
        String line = null;
        List<List<Set<Character>>> s1 = new LinkedList<>();
        List<Set<Character>> currentList = new LinkedList<>();
        while ((line = reader.readLine()) != null) {
            if (line.equals("")) {
                s1.add(currentList);
                currentList = new LinkedList<>();
                continue;
            }
            Set<Character> person = new HashSet<>();
            currentList.add(person);
            for (char c : line.toCharArray()) {
                person.add(c);
            }
        }
        s1.add(currentList);

        int c = 0;
        for (List<Set<Character>> sets : s1) {
            Set<Character> all = new HashSet<>();
            for (Set<Character> set : sets) {
                all.addAll(set);
            }
            int _c = 0;
            for (Set<Character> set : sets) {
                all.retainAll(set);
            }
            c += all.size();
        }

        System.out.println(c);
    }

}
